var fs = require('fs');

function renderHTML(inner) {
    var style = fs.readFileSync(__dirname + '/style.css');
    return (
        '<!DOCTYPE html>' +
        '<html lang="en">' +
            '<head>' +
                '<title>SVG images</title>' +
                '<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">' +
                '<meta name="viewport" content="width=device-width">' +
                '<style>' +
                    style +
                '</style>' +
            '</head>' +
            '<body>' +
                '<h1>SVG images</h1>' +
                '<ul>' +
                    inner +
                '</ul>' +
                '<footer>' +
                    'Generated by ' +
                    '<a href="https://github.com/ykiu/gulp-svg-gallery">' +
                        'gulp-svg-gallery' +
                    '</a>' +
                '</footer>' +
            '</body>' +
        '</html>'
    );
}

function renderItem(name, svg, description) {
    return (
        '<li>' +
            '<h3>' +
                name +
            '</h3>' +
            (svg || '') +
            '<p>' +
                (description || '') +
            '</p>' +
        '</li>'
    );
}

function render(context) {
    var innerHTML = '';
    for (kv of Object.entries(context.main)) {
        var name = kv[0];
        var svg = kv[1]['svg'];
        var desc = kv[1]['desc'];
        innerHTML += renderItem(name, svg, desc);
    }
    var html = renderHTML(innerHTML);
    return html;
}

module.exports = render;
